version: '3.5'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.lo:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - '8929:8929'
      - '2224:2224'
    volumes:
      - '$PWD/data/config:/etc/gitlab'
      - '$PWD/data/logs:/var/log/gitlab'
      - '$PWD/data/data:/var/opt/gitlab'
      - '$PWD/sshd_config:/assets/sshd_config'
    networks:
      gitlab:
        aliases:
          - gitlab.lo
networks:
  gitlab:
    name: localci
