version: '3.7'
services:
  jenkins-master:
    image: 'jenkins/jenkins:lts'
    hostname: jenkins
    domainname: lo
    ports:
      - '80:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
      - '$PWD/data:/var/jenkins_home'
    networks:
      jenkins:
        aliases:
          - jenkins.lo
volumes:
  jenkins_data:
    driver: local
networks:
  jenkins:
    name: localci
